### ISSUE TITLE
可以把酷安写的几篇教程再发出来么？

### ISSUE THREAD

**Issue by tangli159** [i-Fyn/oppostore#1]
之前有看到您的教程，感觉很有用，放进了收藏夹。但是现在都没有啦。可以请求您把几篇教程放出来或者私发么，谢谢您的付出。

**Comment by i-Fyn** [comment]
酷安东西已经全删了，后面有机会再做。

**Comment by tangli159** [comment]
> 酷安东西已经全删了，后面有机会再做。

好的 谢谢ヽ(^0^)ﾉ
